version: '3.8'

services:
  app:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - postgres
      - elasticsearch

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=luffy
      - POSTGRES_PASSWORD=luffy
      - POSTGRES_DB=yt-search-service
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U luffy" ]
      interval: 10s
      retries: 5
      timeout: 5s

  elasticsearch:
    image: elasticsearch:8.13.0
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - elasticnet

  kibana:
    image: kibana:8.13.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elasticnet

networks:
  elasticnet:
    driver: bridge
